### ISSUE TITLE
Deserialize gives error on valid values

### ISSUE THREAD

**Issue by gerdus** [madarche/mcf-js#10]
On using Deserialize it gives error if you have pbkdf2-sha256 as identifier and base64 encoded key/salt

Regex should be expanded to include +,/ and = since they are used if you use buffer.toString('base64')

Performing the validation checks on serialize would also be a good idea.

Thank you

**Comment by madarche** [comment]
Thanks @gerdus for the report. I'm publishing a new version on NPM in a short time.

**Comment by madarche** [comment]
@gerdus:  mcf@2.0.4 has been published
